experiment:
  name: Adam_vs_SGD_on_MNIST
  seed: 42

model:
  layers:
    - { nodes: 128, activation: relu }
    - { nodes: 64, activation: relu }
    - { nodes: 10, activation: softmax }

data:
  name: MNIST
  path: ./datasets/
  split:
    train_percent: 80
    test_percent: 20

training:
  optimizer:
    name: Adam
    params:
      learning_rate: 0.001
  epochs: 50
  batch_size: 32
